version: '2.1'

services:
  spring-boot:
    image: com.example/demo:latest
    ports:
      - "9999:9999/tcp"
  nginx-auto-ssl:
    image: valian/docker-nginx-auto-ssl
    restart: on-failure
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
#    volumes:
#      - ./ssl-data:/etc/resty-auto-ssl
    environment:
      - ALLOWED_DOMAINS=bookstorage.kr
      - SITES=bookstorage.kr=spring-boot:9999;*.bookstorage.kr=spring-boot:9999
      - FORCE_HTTPS=true
